# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-12-12 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocemr", "0005_customizedtextfield"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customizedtextfield",
            name="id",
        ),
        migrations.AlterField(
            model_name="customizedtextfield",
            name="fieldName",
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
